Internationalization of mail
wolox-training/fc-rails pull request #21
Opened 2018-09-13 19:02 UTC by fedecvz

## Summary:
Internationalization of mail

## Trello card:
https://trello.com/c/HHLQDFsf/27-internacionalizar-el-email
![notification_rent_2](https://user-images.githubusercontent.com/8448729/45509528-321f5580-b76e-11e8-9748-355563cac4b1.png)

2018-09-17 20:04 UTC, juanisierra requested changes

2018-09-17 20:04 UTC, juanisierra commented on .env
> +MAILER_USERNAME=e7bcfe7c9a714b
Delete please

2018-09-17 20:04 UTC, juanisierra commented on app/controllers/api/v1/rents_controller.rb
> +        rent.save!
Save it once

2018-09-17 20:23 UTC, ziflit requested changes

2018-09-19 20:14 UTC, ziflit approved these changes

2018-09-19 20:22 UTC, juanisierra approved these changes

2018-09-19 21:16 UTC, closed without merging